/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.sql.PreparedStatement;
import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Toolkit;
import java.awt.Frame;
import javax.swing.SwingUtilities;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jobelle
 */
public class AttendanceLogInst extends BaseFrame {

    private MainPageInst mainPage;
    private Connection conn;
    private StudentRepo dao;                // <- changed to StudentRepo
    private String loggedInInstID;
    private boolean integrationInitialized = false;

    // user info
    private String InstID;
    private String Role;
    private String FName;
    private String MName;
    private String LName;

    public AttendanceLogInst(MainPageInst mainPage) {
        super(mainPage);
        this.mainPage = mainPage;
        initComponents();
        setCenter();
        initConnection();
        if (dao == null && conn != null) dao = new StudentRepo(conn); // <- changed
        addTableRowPopup(tableAttendance, dao);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNavigation = new javax.swing.JPanel();
        BackHome = new javax.swing.JLabel();
        IDScanner = new customElements.NewButton();
        BViewClass = new customElements.NewButton();
        BViewProfile = new customElements.NewButton();
        BLogout = new customElements.NewButton();
        jLabel1 = new javax.swing.JLabel();
        comboCourse = new customElements.RoundedComboBox();
        comboSubject = new customElements.RoundedComboBox();
        comboYear = new customElements.RoundedComboBox();
        comboSection = new customElements.RoundedComboBox();
        savePDF = new customElements.NewButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAttendance = new customElements.CustomAttendanceTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelNavigation.setBackground(new java.awt.Color(15, 23, 42));
        panelNavigation.setPreferredSize(new java.awt.Dimension(675, 66));

        BackHome.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setText("< Home");
        BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeMouseClicked(evt);
            }
        });

        IDScanner.setText("ID Scanner");
        IDScanner.setToolTipText("");
        IDScanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDScannerActionPerformed(evt);
            }
        });

        BViewClass.setText("View Classes");
        BViewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BViewClassActionPerformed(evt);
            }
        });

        BViewProfile.setText("View Profile");
        BViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BViewProfileActionPerformed(evt);
            }
        });

        BLogout.setText("Logout");
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Attendance Log");

        javax.swing.GroupLayout panelNavigationLayout = new javax.swing.GroupLayout(panelNavigation);
        panelNavigation.setLayout(panelNavigationLayout);
        panelNavigationLayout.setHorizontalGroup(
            panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BackHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BViewClass, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelNavigationLayout.setVerticalGroup(
            panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackHome)
                    .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BViewClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        comboCourse.setBackground(new java.awt.Color(228, 226, 226));
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Course", "Computer Science", "Information Technology", "Bachelor in Library and Information Science", "Diploma in Computer Technology", " " }));
        comboCourse.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSubject.setBackground(new java.awt.Color(228, 226, 226));
        comboSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject", " " }));
        comboSubject.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboYear.setBackground(new java.awt.Color(228, 226, 226));
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1", "2", "3", "4" }));
        comboYear.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSection.setBackground(new java.awt.Color(228, 226, 226));
        comboSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section", "A", "B", "C", "D", "E" }));
        comboSection.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        savePDF.setText("Save as PDF");
        savePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePDFActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tableAttendance);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325)
                        .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BViewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BViewClassActionPerformed
        ViewClasses VC = mainPage.getViewClasses(); // reuse existing instance
        VC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BViewClassActionPerformed

    private void IDScannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDScannerActionPerformed
        this.setVisible(false);
        mainPage.setVisible(true);
    }//GEN-LAST:event_IDScannerActionPerformed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        boolean logoutClicked = true;

        if (logoutClicked){
            this.dispose();

            LoginForm LF = new LoginForm();
            LF.setVisible(true);
        }
    }//GEN-LAST:event_BLogoutActionPerformed

    private void BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseClicked
            this.setVisible(false);
            mainPage.setVisible(true);
    }//GEN-LAST:event_BackHomeMouseClicked

    private void BViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BViewProfileActionPerformed
        ViewProfile VP = new ViewProfile (mainPage);
        VP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BViewProfileActionPerformed

    private void savePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePDFActionPerformed
        PDFExportUtil.exportTable(this, tableAttendance);
    }//GEN-LAST:event_savePDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainPageInst mainPage = new MainPageInst();  
                AttendanceLogInst attendanceLog = new AttendanceLogInst(mainPage);
                attendanceLog.setVisible(true);
            }
        });
    }
    
    private void setCenter() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int left = (d.width - this.getWidth()) / 2;
        int top = (d.height - this.getHeight()) / 2;
        this.setLocation(left, top);
    }
    
    
    
    public void setLoggedInUser(String InstID, String Role, String FName, String MName, String LName) {
        // Save to fields for later use
        this.InstID = InstID;
        this.Role = Role;
        this.FName = FName;
        this.MName = MName;
        this.LName = LName;
        
        this.loggedInInstID = InstID;
        initIntegration(); // call here so loggedInInstID is ready
    }
    
    
    /** Initialize database connection */
    private void initConnection() {
        try {
            conn = DBConfig.getConnection();
            dao = new StudentRepo(conn);
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Database connection failed!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Connection getConnection() {
        return conn;
    }
    
    public void setConnection(Connection conn) {
        this.conn = conn;
    }

    public void setInstructorID(String instID) {
        this.InstID = instID;
    }

    private void initIntegration() {
        if (integrationInitialized) return;
        integrationInitialized = true;

        if (conn == null) return; // avoid null pointer

        InstructorAttendanceTable attTable = new InstructorAttendanceTable(conn, tableAttendance);

        Runnable reloadTable = () -> {
            Integer selectedCourseID = comboCourse.getSelectedIndex() <= 0 ? null : comboCourse.getSelectedIndex();
            Integer selectedSubID = comboSubject.getSelectedIndex() <= 0 ? null : comboSubject.getSelectedIndex();
            Integer selectedYear = null;
            if (comboYear.getSelectedIndex() > 0) {
                try {
                    selectedYear = Integer.valueOf(comboYear.getSelectedItem().toString());
                } catch (NumberFormatException ex) {
                    selectedYear = null;
                }
            }
            String selectedSection = comboSection.getSelectedIndex() <= 0 ? null : (String) comboSection.getSelectedItem();

            attTable.loadData(loggedInInstID, selectedCourseID, selectedSubID, selectedYear, selectedSection);
        };

        comboCourse.addActionListener(e -> reloadTable.run());
        comboSubject.addActionListener(e -> reloadTable.run());
        comboYear.addActionListener(e -> reloadTable.run());
        comboSection.addActionListener(e -> reloadTable.run());

        reloadTable.run();
    }

    // ------------------- RIGHT-CLICK EDIT/DELETE -------------------
    private void addTableRowPopup(JTable tableAttendance, StudentRepo dao) { // <- param type changed
        JPopupMenu popup = new JPopupMenu();
        JMenuItem editItem = new JMenuItem("Edit");
        JMenuItem deleteItem = new JMenuItem("Delete");
        popup.add(editItem);
        popup.add(deleteItem);

        tableAttendance.setComponentPopupMenu(popup);

        tableAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = tableAttendance.rowAtPoint(e.getPoint());
                if (row != -1) {
                    tableAttendance.setRowSelectionInterval(row, row);
                }
            }
        });

        // EDIT handler unchanged (uses mapper and StudentEditLauncher)
        editItem.addActionListener(e -> {
            RowToStudentMapper attMapper = (model, modelRow) -> {
                String course  = UiUtils.safeToString(model.getValueAt(modelRow, 0));
                String subject = UiUtils.safeToString(model.getValueAt(modelRow, 1));
                String lname   = UiUtils.safeToString(model.getValueAt(modelRow, 2));
                String fname   = UiUtils.safeToString(model.getValueAt(modelRow, 3));
                String mname   = UiUtils.safeToString(model.getValueAt(modelRow, 4));
                String year    = UiUtils.safeToString(model.getValueAt(modelRow, 5));
                String section = UiUtils.safeToString(model.getValueAt(modelRow, 6));
                String studID  = ""; // if model contains StudID, populate here
                return new StudentRow(studID, fname, mname, lname, subject, course, year, section);
            };

            Frame owner = (Frame) SwingUtilities.getWindowAncestor(tableAttendance);

            StudentEditLauncher.openEditDialogFromTable(owner, tableAttendance, dao, attMapper, () -> {
                comboCourse.dispatchEvent(new java.awt.event.ActionEvent(comboCourse, java.awt.event.ActionEvent.ACTION_PERFORMED, ""));
            });
        });

        // deleteItem ActionListener body (inside addTableRowPopup)
        deleteItem.addActionListener(e -> {
            int viewRow = tableAttendance.getSelectedRow();
            if (viewRow == -1) return;
            int modelRow = tableAttendance.convertRowIndexToModel(viewRow);
            DefaultTableModel model = (DefaultTableModel) tableAttendance.getModel();

            int colCount = model.getColumnCount();
            int attendIdCol = Math.max(0, colCount - 2);
            int studIdCol = Math.max(0, colCount - 1);

            String attendId = UiUtils.safeToString(model.getValueAt(modelRow, attendIdCol));
            String studID = UiUtils.safeToString(model.getValueAt(modelRow, studIdCol));

            if (attendId != null && !attendId.isEmpty()) {
                int confirm = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to delete this attendance record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) return;

                boolean ok = dao == null ? false : dao.deleteAttendanceById(attendId);
                if (!ok) {
                    JOptionPane.showMessageDialog(null, "Error deleting attendance from database!");
                    return;
                }
                model.removeRow(modelRow);
                return;
            }

            if (studID != null && !studID.isEmpty()) {
                int confirm = JOptionPane.showConfirmDialog(null,
                        "Attendance record does not include its internal ID. Do you want to delete all matching attendance records for student " + studID + " (may delete multiple rows)?",
                        "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) return;

                boolean ok = dao == null ? false : dao.deleteAttendanceForStudOnDate(studID, null);
                if (!ok) {
                    JOptionPane.showMessageDialog(null, "Error deleting attendance from database!");
                    return;
                }
                model.removeRow(modelRow);
                return;
            }

            JOptionPane.showMessageDialog(null,
                    "Couldn't determine a unique attendance record to delete. Please include AttendID/StudID in the table model (hidden columns are fine).",
                    "Delete failed", JOptionPane.ERROR_MESSAGE);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customElements.NewButton BLogout;
    private customElements.NewButton BViewClass;
    private customElements.NewButton BViewProfile;
    private javax.swing.JLabel BackHome;
    private customElements.NewButton IDScanner;
    private customElements.RoundedComboBox comboCourse;
    private customElements.RoundedComboBox comboSection;
    private customElements.RoundedComboBox comboSubject;
    private customElements.RoundedComboBox comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelNavigation;
    private customElements.NewButton savePDF;
    private customElements.CustomAttendanceTable tableAttendance;
    // End of variables declaration//GEN-END:variables
}
