/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Frame;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;


/**
 *
 * @author Jobelle
 */
public class AttendanceLogInst extends BaseFrame {

    private HomePage homePage;
    private Connection conn;
    private StudentRepo dao;                // <- changed to StudentRepo
    private String loggedInInstID;
    private boolean integrationInitialized = false;

    // user info
    private String InstID;
    private String Role;
    private String FName;
    private String MName;
    private String LName;

    public AttendanceLogInst(HomePage homePage) {
        super(homePage);
        this.homePage = homePage;
        initComponents();
        setCenter();
        useCustomBackground();
        initConnection();
        if (dao == null && conn != null) dao = new StudentRepo(conn);
        addTableRowPopup(tableAttendance, dao);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboCourse = new customElements.RoundedComboBox();
        comboSubject = new customElements.RoundedComboBox();
        comboYear = new customElements.RoundedComboBox();
        comboSection = new customElements.RoundedComboBox();
        savePDF = new customElements.NewButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAttendance = new customElements.CustomAttendanceTable();
        BViewClass = new customElements.NewButton();
        IDScanner = new customElements.NewButton();
        jLabel1 = new javax.swing.JLabel();
        BackHome = new javax.swing.JLabel();
        Logout = new customElements.NewButton();
        btnViewProfile = new customElements.NewButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 17, 84));

        comboCourse.setBackground(new java.awt.Color(228, 226, 226));
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Course", "Computer Science", "Information Technology", "Bachelor in Library and Information Science", "Diploma in Computer Technology", " " }));
        comboCourse.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSubject.setBackground(new java.awt.Color(228, 226, 226));
        comboSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject", " " }));
        comboSubject.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboYear.setBackground(new java.awt.Color(228, 226, 226));
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1", "2", "3", "4" }));
        comboYear.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSection.setBackground(new java.awt.Color(228, 226, 226));
        comboSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section", "A", "B", "C", "D", "E" }));
        comboSection.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        savePDF.setText("Save as PDF");
        savePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePDFActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tableAttendance);

        BViewClass.setText("View Classes");
        BViewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BViewClassActionPerformed(evt);
            }
        });

        IDScanner.setText("ID Scanner");
        IDScanner.setToolTipText("");
        IDScanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDScannerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Attendance Log");

        BackHome.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setText("< Home");
        BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeMouseClicked(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(37, 99, 235));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BackHome)
                            .addGap(294, 294, 294))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(325, 325, 325)
                                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(25, 25, 25)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BViewClass, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BViewClass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BackHome)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BViewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BViewClassActionPerformed
        ViewClasses VC = homePage.getViewClasses(); // reuse existing instance
        VC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BViewClassActionPerformed

    private void IDScannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDScannerActionPerformed
        MainPageInst mp = new MainPageInst(homePage);
        mp.setLoggedInUser(this.InstID, this.Role, this.FName, this.MName, this.LName);
        mp.setVisible(true);
    }//GEN-LAST:event_IDScannerActionPerformed

    private void BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseClicked
            this.setVisible(false);
            homePage.setVisible(true);
    }//GEN-LAST:event_BackHomeMouseClicked

    private void savePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePDFActionPerformed
        // Build subtitle from active filters (only include non-default selections)
        String course = (comboCourse.getSelectedIndex() > 0) ? comboCourse.getSelectedItem().toString().trim() : "";
        String year = (comboYear.getSelectedIndex() > 0) ? comboYear.getSelectedItem().toString().trim() : "";
        String section = (comboSection.getSelectedIndex() > 0) ? comboSection.getSelectedItem().toString().trim() : "";

        String classInfo = String.join(" ",
                (course.isEmpty() ? "" : course),
                (year.isEmpty() ? "" : year),
                (section.isEmpty() ? "" : section)
        ).trim();

        String title = "Class Attendance" + (classInfo.isEmpty() ? "" : ("\n BS " + classInfo));

        PDFExportUtil.exportTable(this, tableAttendance, title);
    }//GEN-LAST:event_savePDFActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        boolean logoutClicked = true;

        if (logoutClicked){
            this.dispose();

            LoginForm LF = new LoginForm();
            LF.setVisible(true);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        dialogViewProfile dvp = new dialogViewProfile(this, true);
        dvp.setLoggedInUser(this.InstID, this.Role, this.FName, this.MName, this.LName);
        dvp.setVisible(true);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceLogInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomePage homePage = new HomePage();  
                AttendanceLogInst attendanceLog = new AttendanceLogInst(homePage);
                attendanceLog.setVisible(true);
            }
        });
    }
    
    
    
    private void setCenter() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int left = (d.width - this.getWidth()) / 2;
        int top = (d.height - this.getHeight()) / 2;
        this.setLocation(left, top);
    }

    private void useCustomBackground() {
        try {
            // Load background image
            final java.awt.image.BufferedImage bg = javax.imageio.ImageIO.read(
                getClass().getResource("/images/headerQRrive.jpg")
            );

            javax.swing.JPanel bgPanel = new javax.swing.JPanel(new java.awt.BorderLayout()) {
                @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                    if (bg == null) return;

                    java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                    try {
                        // High quality rendering hints
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                                            java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING,
                                            java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                        // Draw the background image scaled to fill the panel (maintain aspect if you prefer)
                        int w = getWidth();
                        int h = getHeight();
                        g2.drawImage(bg, 0, 0, w, h, this);
                    } finally {
                        g2.dispose();
                    }
                }
            };

            jPanel1.setOpaque(false);
            bgPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

            setContentPane(bgPanel);
            pack(); // resize window correctly
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Override to refresh when caller supplies the logged-in user (HomePage reuses instances)
    @Override
    public void setLoggedInUser(String InstID, String Role, String FName, String MName, String LName) {
        this.InstID = InstID;
        this.Role = Role;
        this.FName = FName;
        this.MName = MName;
        this.LName = LName;

        this.loggedInInstID = InstID;

        // re-init integration (reload table + combos)
        initIntegration();
    }
    

    /** Initialize database connection */
    private void initConnection() {
        try {
            conn = DBConfig.getConnection();
            dao = new StudentRepo(conn);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Database connection failed!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Connection getConnection() {
        return conn;
    }
    
    public void setConnection(Connection conn) {
        this.conn = conn;
    }

    public void setInstructorID(String instID) {
        this.InstID = instID;
    }
    
    private void initIntegration() {
        if (conn == null || loggedInInstID == null) return;

        // create the attendance table wrapper and load data for the current instructor
        InstructorAttendanceTable attTable = new InstructorAttendanceTable(conn, tableAttendance);
        attTable.loadData(loggedInInstID, null, null, null, null);
        
        // populate combos from DB for this instructor
        populateFiltersForInstructor();
        integrationInitialized = true;
    }

    private void populateFiltersForInstructor() {
        if (dao == null || loggedInInstID == null) return;

        List<String> courses = dao.listCoursesForInstructor(loggedInInstID);
        DefaultComboBoxModel<String> courseModel = new DefaultComboBoxModel<>();
        courseModel.addElement("Course");
        for (String c : courses) courseModel.addElement(c);
        comboCourse.setModel(courseModel);

        DefaultComboBoxModel<String> subjectModel = new DefaultComboBoxModel<>();
        subjectModel.addElement("Subject");
        List<String> subjects = dao.listSubjectsForInstructor(loggedInInstID, null);
        for (String s : subjects) subjectModel.addElement(s);
        comboSubject.setModel(subjectModel);

        DefaultComboBoxModel<String> yearModel = new DefaultComboBoxModel<>();
        yearModel.addElement("Year");
        List<String> years = dao.listYearsForInstructor(loggedInInstID);
        for (String y : years) yearModel.addElement(y);
        comboYear.setModel(yearModel);

        DefaultComboBoxModel<String> sectionModel = new DefaultComboBoxModel<>();
        sectionModel.addElement("Section");
        List<String> sections = dao.listSectionsForInstructor(loggedInInstID, null);
        for (String s : sections) sectionModel.addElement(s);
        comboSection.setModel(sectionModel);
    }

    // ------------------- RIGHT-CLICK EDIT/DELETE -------------------
    private void addTableRowPopup(JTable tableAttendance, StudentRepo dao) { // <- param type changed
        JPopupMenu popup = new JPopupMenu();
        JMenuItem editItem = new JMenuItem("Edit");
        JMenuItem deleteItem = new JMenuItem("Delete");
        popup.add(editItem);
        popup.add(deleteItem);

        tableAttendance.setComponentPopupMenu(popup);

        tableAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = tableAttendance.rowAtPoint(e.getPoint());
                if (row != -1) {
                    tableAttendance.setRowSelectionInterval(row, row);
                }
            }
        });

        // EDIT handler unchanged (uses mapper and StudentEditLauncher)
        editItem.addActionListener(e -> {
            RowToStudentMapper attMapper = (model, modelRow) -> {
                String course  = UiUtils.safeToString(model.getValueAt(modelRow, 0));
                String subject = UiUtils.safeToString(model.getValueAt(modelRow, 1));
                String lname   = UiUtils.safeToString(model.getValueAt(modelRow, 2));
                String fname   = UiUtils.safeToString(model.getValueAt(modelRow, 3));
                String mname   = UiUtils.safeToString(model.getValueAt(modelRow, 4));
                String year    = UiUtils.safeToString(model.getValueAt(modelRow, 5));
                String section = UiUtils.safeToString(model.getValueAt(modelRow, 6));
                String studID  = ""; // if model contains StudID, populate here
                return new StudentRow(studID, fname, mname, lname, subject, course, year, section);
            };

            Frame owner = (Frame) SwingUtilities.getWindowAncestor(tableAttendance);

            StudentEditLauncher.openEditDialogFromTable(owner, tableAttendance, dao, attMapper, () -> {
                comboCourse.dispatchEvent(new java.awt.event.ActionEvent(comboCourse, java.awt.event.ActionEvent.ACTION_PERFORMED, ""));
            });
        });

        // deleteItem ActionListener body (inside addTableRowPopup)
        deleteItem.addActionListener(e -> {
            int viewRow = tableAttendance.getSelectedRow();
            if (viewRow == -1) return;
            int modelRow = tableAttendance.convertRowIndexToModel(viewRow);
            DefaultTableModel model = (DefaultTableModel) tableAttendance.getModel();

            int colCount = model.getColumnCount();
            int attendIdCol = Math.max(0, colCount - 2);
            int studIdCol = Math.max(0, colCount - 1);

            String attendId = UiUtils.safeToString(model.getValueAt(modelRow, attendIdCol));
            String studID = UiUtils.safeToString(model.getValueAt(modelRow, studIdCol));

            if (attendId != null && !attendId.isEmpty()) {
                int confirm = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to delete this attendance record?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) return;

                boolean ok = dao == null ? false : dao.deleteAttendanceById(attendId);
                if (!ok) {
                    JOptionPane.showMessageDialog(null, "Error deleting attendance from database!");
                    return;
                }
                model.removeRow(modelRow);
                return;
            }

            if (studID != null && !studID.isEmpty()) {
                int confirm = JOptionPane.showConfirmDialog(null,
                        "Attendance record does not include its internal ID. Do you want to delete all matching attendance records for student " + studID + " (may delete multiple rows)?",
                        "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (confirm != JOptionPane.YES_OPTION) return;

                boolean ok = dao == null ? false : dao.deleteAttendanceForStudOnDate(studID, null);
                if (!ok) {
                    JOptionPane.showMessageDialog(null, "Error deleting attendance from database!");
                    return;
                }
                model.removeRow(modelRow);
                return;
            }

            JOptionPane.showMessageDialog(null,
                    "Couldn't determine a unique attendance record to delete. Please include AttendID/StudID in the table model (hidden columns are fine).",
                    "Delete failed", JOptionPane.ERROR_MESSAGE);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customElements.NewButton BViewClass;
    private javax.swing.JLabel BackHome;
    private customElements.NewButton IDScanner;
    private customElements.NewButton Logout;
    private customElements.NewButton btnViewProfile;
    private customElements.RoundedComboBox comboCourse;
    private customElements.RoundedComboBox comboSection;
    private customElements.RoundedComboBox comboSubject;
    private customElements.RoundedComboBox comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private customElements.NewButton savePDF;
    private customElements.CustomAttendanceTable tableAttendance;
    // End of variables declaration//GEN-END:variables
}
