/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Forms;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Jobelle
 */

public class dialogEditInfo extends javax.swing.JDialog {

    private StudentRepo dao;        // <- changed to StudentRepo
    private String studentID;      // selected student ID (StudID)

    /**
     * Preferred constructor: accepts StudentRepo.
     */
    // Preferred constructor: accepts StudentRepo.
    public dialogEditInfo(Frame parent, boolean modal, StudentRepo dao, String studentID) {
        super(parent, modal);
        this.dao = dao;
        this.studentID = studentID;
        initComponents(); // create UI (GroupLayout attached to jPanel1 here)
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(parent);
    }

    // Backwards-compatible constructor: accepts Connection and wraps it in a repo.
    public dialogEditInfo(Frame parent, boolean modal, java.sql.Connection conn, String studentID) {
        super(parent, modal);
        this.dao = conn == null ? null : new StudentRepo(conn);
        this.studentID = studentID;
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(parent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbYear = new customElements.RoundedComboBox();
        cbSection = new customElements.RoundedComboBox();
        buttonSave = new customElements.NewButton();
        lblEditStudInfo = new javax.swing.JLabel();
        buttonCancel = new customElements.NewButton();
        lblFName = new javax.swing.JLabel();
        tfFName = new customElements.NewTextField();
        lblMName = new javax.swing.JLabel();
        tfMName = new customElements.NewTextField();
        lblLName = new javax.swing.JLabel();
        tfLName = new customElements.NewTextField();
        lblSub = new javax.swing.JLabel();
        tfSubject = new customElements.NewTextField();
        lblCourse = new javax.swing.JLabel();
        tfCourse = new customElements.NewTextField();
        lblYear = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        cbYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbYearKeyReleased(evt);
            }
        });

        cbSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        cbSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbSectionKeyReleased(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        lblEditStudInfo.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblEditStudInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditStudInfo.setText("Edit Student Information");

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        lblFName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblFName.setText("First Name");

        tfFName.setText("newTextField1");
        tfFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFNameKeyReleased(evt);
            }
        });

        lblMName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMName.setText("Middle Name");

        tfMName.setText("newTextField1");
        tfMName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMNameKeyReleased(evt);
            }
        });

        lblLName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblLName.setText("Last Name");

        tfLName.setText("newTextField1");
        tfLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLNameKeyReleased(evt);
            }
        });

        lblSub.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblSub.setText("Subject");

        tfSubject.setText("newTextField1");
        tfSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSubjectKeyReleased(evt);
            }
        });

        lblCourse.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblCourse.setText("Course");

        tfCourse.setText("newTextField1");
        tfCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCourseKeyReleased(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblYear.setText("Year");

        lblSection.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblSection.setText("Section");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditStudInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblYear)
                                    .addComponent(lblFName)
                                    .addComponent(lblMName)
                                    .addComponent(lblLName)
                                    .addComponent(lblSub)
                                    .addComponent(lblCourse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSection)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSection, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfFName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfMName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblEditStudInfo)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMName)
                    .addComponent(tfMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLName)
                    .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSub)
                    .addComponent(tfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(tfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(lblSection)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        JOptionPane.showMessageDialog(this, "Student information updated successfully!");
        saveChanges();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void tfFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFNameKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_tfFNameKeyReleased

    private void tfMNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMNameKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_tfMNameKeyReleased

    private void tfLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLNameKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_tfLNameKeyReleased

    private void tfSubjectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSubjectKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_tfSubjectKeyReleased

    private void tfCourseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCourseKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_tfCourseKeyReleased

    private void cbYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbYearKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_cbYearKeyReleased

    private void cbSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSectionKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonSave.doClick(500);
        }
    }//GEN-LAST:event_cbSectionKeyReleased

    private void setCenter() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int left = (d.width - this.getWidth()) / 2;
        int top = (d.height - this.getHeight()) / 2;
        this.setLocation(left, top);
    }
    
    // replace the existing saveChanges() method with this
    public void saveChanges() {
        if (dao == null) {
            JOptionPane.showMessageDialog(this, "No database connection available", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // Build the updated values from the dialog fields
            StudentRow updated = new StudentRow(
                studentID, // may be empty; we'll resolve below if needed
                tfFName.getText(),
                tfMName.getText(),
                tfLName.getText(),
                tfSubject.getText(),
                tfCourse.getText(),
                cbYear.getSelectedItem() == null ? "" : cbYear.getSelectedItem().toString(),
                cbSection.getSelectedItem() == null ? "" : cbSection.getSelectedItem().toString()
            );

            // Ensure we have a valid StudID to update
            String targetStudID = (studentID == null) ? "" : studentID.trim();
            if (targetStudID.isEmpty()) {
                // Try to resolve StudID by matching the student row values
                String found = dao.findStudID(updated);
                if (found == null || found.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                        "Cannot determine the student's ID (StudID). Please open the edit dialog from a student row or ensure the student exists in the database.",
                        "Can't locate student", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                targetStudID = found;
            }

            boolean ok = dao.updateStudent(targetStudID, updated);
            if (ok) {
                //JOptionPane.showMessageDialog(this, "Student information updated successfully!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Update failed");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating database: " + ex.getMessage(), "DB Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void loadData(String FName, String MName, String LName, String SubName, String CourseName, String Year, String Section) {
        // set text fields
        tfFName.setText(FName);
        tfMName.setText(MName);
        tfLName.setText(LName);
        tfSubject.setText(SubName);
        tfCourse.setText(CourseName);

        // select Year/Section robustly: add value if not present
        if (Year != null && !Year.isEmpty()) {
            DefaultComboBoxModel yearModel = (DefaultComboBoxModel) cbYear.getModel();
            if (yearModel.getIndexOf(Year) == -1) yearModel.addElement(Year);
            cbYear.setSelectedItem(Year);
        } else {
            cbYear.setSelectedIndex(-1);
        }

        if (Section != null && !Section.isEmpty()) {
            DefaultComboBoxModel sectionModel = (DefaultComboBoxModel) cbSection.getModel();
            if (sectionModel.getIndexOf(Section) == -1) sectionModel.addElement(Section);
            cbSection.setSelectedItem(Section);
        } else {
            cbSection.setSelectedIndex(-1);
        }

        // Refresh UI
        javax.swing.SwingUtilities.invokeLater(() -> {
            tfFName.revalidate(); tfFName.repaint();
            tfMName.revalidate(); tfMName.repaint();
            tfLName.revalidate(); tfLName.repaint();
            tfSubject.revalidate(); tfSubject.repaint();
            tfCourse.revalidate(); tfCourse.repaint();
            cbYear.revalidate(); cbYear.repaint();
            cbSection.revalidate(); cbSection.repaint();
        });
    }

    // getters used by launcher
    public customElements.NewButton getButtonSave() { return buttonSave; }
    public customElements.NewButton getButtonCancel() { return buttonCancel; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customElements.NewButton buttonCancel;
    private customElements.NewButton buttonSave;
    private customElements.RoundedComboBox cbSection;
    private customElements.RoundedComboBox cbYear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblEditStudInfo;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMName;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblYear;
    private customElements.NewTextField tfCourse;
    private customElements.NewTextField tfFName;
    private customElements.NewTextField tfLName;
    private customElements.NewTextField tfMName;
    private customElements.NewTextField tfSubject;
    // End of variables declaration//GEN-END:variables
}
