/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;
   
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.JPanel;
/**
 *
 * @author Jobelle
 */
public class HeaderPanel extends JPanel {
    private final Image bg;
    private final int headerHeight;

    /**
     * Create a HeaderPanel with the given background image and height.
     * Use width 0 for flexible width; the layout manager will size it.
     *
     * @param bgImage the image to display (may be null)
     * @param height preferred height in pixels
     */
    public HeaderPanel(Image bgImage, int height) {
        this.bg = bgImage;
        this.headerHeight = Math.max(1, height);
        setOpaque(false);
        setPreferredSize(new Dimension(0, this.headerHeight));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (bg == null) return;

        Graphics2D g2 = (Graphics2D) g.create();
        try {
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                                RenderingHints.VALUE_INTERPOLATION_BICUBIC);
            g2.setRenderingHint(RenderingHints.KEY_RENDERING,
                                RenderingHints.VALUE_RENDER_QUALITY);
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                                RenderingHints.VALUE_ANTIALIAS_ON);

            // Draw the image filling the header panel area.
            // Keeps aspect ratio by scaling to cover the area (center-crop behavior).
            int pw = getWidth();
            int ph = getHeight();
            int iw = bg.getWidth(null);
            int ih = bg.getHeight(null);
            if (iw <= 0 || ih <= 0) {
                g2.drawImage(bg, 0, 0, pw, ph, this);
                return;
            }

            double scale = Math.max((double) pw / iw, (double) ph / ih);
            int sw = (int) Math.round(iw * scale);
            int sh = (int) Math.round(ih * scale);
            int sx = (pw - sw) / 2;
            int sy = (ph - sh) / 2;

            g2.drawImage(bg, sx, sy, sw, sh, this);
        } finally {
            g2.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
