/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Forms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author Jobelle
 */
public class SavePDFDialog extends java.awt.Dialog {
    private String selectedSize = null;
    private boolean confirmed = false;


    /**
     * Creates new form SavePDFDialog
     */
    public SavePDFDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setCenter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbPaperSize = new customElements.RoundedComboBox();
        lblSelect = new javax.swing.JLabel();
        buttonPrint = new customElements.NewButton();
        buttonCancel = new customElements.NewButton();
        lblPrint = new javax.swing.JLabel();
        blbOrientation = new javax.swing.JLabel();
        cbOrientation = new customElements.RoundedComboBox();
        lblMargin = new javax.swing.JLabel();
        cbMargin = new customElements.RoundedComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(15, 23, 42));

        cbPaperSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A4", "Letter", "Legal" }));
        cbPaperSize.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbPaperSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbPaperSizeKeyReleased(evt);
            }
        });

        lblSelect.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblSelect.setForeground(new java.awt.Color(255, 255, 255));
        lblSelect.setText("Size");

        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        lblPrint.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblPrint.setForeground(new java.awt.Color(255, 255, 255));
        lblPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrint.setText("Print Attendance");

        blbOrientation.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        blbOrientation.setForeground(new java.awt.Color(255, 255, 255));
        blbOrientation.setText("Orientation");

        cbOrientation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Portrait", "Landscape", " " }));
        cbOrientation.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbOrientation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbOrientationKeyReleased(evt);
            }
        });

        lblMargin.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMargin.setForeground(new java.awt.Color(255, 255, 255));
        lblMargin.setText("Margin");

        cbMargin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Moderate", "Narrow", "Wide", " " }));
        cbMargin.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbMargin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbMarginKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPaperSize, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(blbOrientation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMargin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPrint)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaperSize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelect))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blbOrientation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMargin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        selectedSize = cbPaperSize.getSelectedItem().toString();
        confirmed = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        confirmed = false;
        selectedSize = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void cbMarginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbMarginKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonPrint.doClick(500);
        }
    }//GEN-LAST:event_cbMarginKeyReleased

    private void cbOrientationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbOrientationKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonPrint.doClick(500);
        }
    }//GEN-LAST:event_cbOrientationKeyReleased

    private void cbPaperSizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbPaperSizeKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            Toolkit.getDefaultToolkit().beep();   
            //System.out.println("ENTER pressed");
            buttonPrint.doClick(500);
        }
    }//GEN-LAST:event_cbPaperSizeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SavePDFDialog dialog = new SavePDFDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public String getSelectedSize() {
        return selectedSize;
    }

    public boolean isConfirmed() {
        return confirmed;
    }
    
    public String getSelectedOrientation() {
        return cbOrientation.getSelectedItem().toString();
    }

    public String getSelectedMargin() {
        return cbMargin.getSelectedItem().toString();
    }

    private void setCenter() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int left = (d.width - this.getWidth()) / 2;
        int top = (d.height - this.getHeight()) / 2;
        this.setLocation(left, top);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbOrientation;
    private customElements.NewButton buttonCancel;
    private customElements.NewButton buttonPrint;
    private customElements.RoundedComboBox cbMargin;
    private customElements.RoundedComboBox cbOrientation;
    private customElements.RoundedComboBox cbPaperSize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMargin;
    private javax.swing.JLabel lblPrint;
    private javax.swing.JLabel lblSelect;
    // End of variables declaration//GEN-END:variables
}
