/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import customElements.Classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;

import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jobelle
 */
public class ViewClasses extends BaseFrame {
    
    private MainPageInst mainPage;
    private Connection conn;
    private StudentRepo dao; // <- changed type
    private String loggedInInstID;
    private boolean integrationInitialized = false;
    
    // user info (needed by setLoggedInUser and other methods)
    private String InstID;
    private String Role;
    private String FName;
    private String MName;
    private String LName;

    public ViewClasses(MainPageInst mainPage) {
        super(mainPage);
        this.mainPage = mainPage;
        this.loggedInInstID = mainPage.getInstructorID();
        initConnection();
        initComponents();
        initIntegration();
        setCenter();
        useCustomBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNavigation = new javax.swing.JPanel();
        BackHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IDScanner = new customElements.NewButton();
        AttendanceLog = new customElements.NewButton();
        BViewProfile = new customElements.NewButton();
        BLogout = new customElements.NewButton();
        comboYear = new customElements.RoundedComboBox();
        comboSection = new customElements.RoundedComboBox();
        savePDF = new customElements.NewButton();
        comboCourse = new customElements.RoundedComboBox();
        comboSubject = new customElements.RoundedComboBox();
        classTable = new customElements.Classes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelNavigation.setBackground(new java.awt.Color(15, 23, 42));

        BackHome.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setText("< Home");
        BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Classes");

        IDScanner.setText("ID Scanner");
        IDScanner.setToolTipText("");
        IDScanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDScannerActionPerformed(evt);
            }
        });

        AttendanceLog.setText("Attendance Log");
        AttendanceLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceLogActionPerformed(evt);
            }
        });

        BViewProfile.setText("View Profile");

        BLogout.setText("Logout");
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavigationLayout = new javax.swing.GroupLayout(panelNavigation);
        panelNavigation.setLayout(panelNavigationLayout);
        panelNavigationLayout.setHorizontalGroup(
            panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BackHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AttendanceLog, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelNavigationLayout.setVerticalGroup(
            panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackHome)
                    .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AttendanceLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        comboYear.setBackground(new java.awt.Color(228, 226, 226));
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1", "2", "3", "4" }));
        comboYear.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSection.setBackground(new java.awt.Color(228, 226, 226));
        comboSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section", "A", "B", "C", "D", "E" }));
        comboSection.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        savePDF.setText("Save as PDF");
        savePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePDFActionPerformed(evt);
            }
        });

        comboCourse.setBackground(new java.awt.Color(228, 226, 226));
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Course", "BS Computer Science", "BS Information Technology", "Bachelor in Library and Information Science", "Diploma in Computer Technology", "" }));
        comboCourse.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSubject.setBackground(new java.awt.Color(228, 226, 226));
        comboSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject", "Object-Oriented Programming", " ", " " }));
        comboSubject.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325)
                        .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(classTable, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseClicked
        this.setVisible(false);
        mainPage.setVisible(true);
    }//GEN-LAST:event_BackHomeMouseClicked

    private void IDScannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDScannerActionPerformed
        this.setVisible(false);
        mainPage.setVisible(true);
    }//GEN-LAST:event_IDScannerActionPerformed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        boolean logoutClicked = true;

        if (logoutClicked){
            this.dispose();

            LoginForm LF = new LoginForm();
            LF.setVisible(true);
        }
    }//GEN-LAST:event_BLogoutActionPerformed

    private void AttendanceLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceLogActionPerformed
        AttendanceLogInst AL = mainPage.getAttendanceLogInst(); // reuse existing instance
        AL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AttendanceLogActionPerformed

    private void savePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePDFActionPerformed
        JTable table = classTable.getTable();
        PDFExportUtil.exportTable(this, table);
    }//GEN-LAST:event_savePDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainPageInst mainPage = new MainPageInst();  
                ViewClasses viewClass = new ViewClasses(mainPage);
                viewClass.setVisible(true);
            }
        });
    }

    private void setCenter() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int left = (d.width - this.getWidth()) / 2;
        int top = (d.height - this.getHeight()) / 2;
        this.setLocation(left, top);
    }
    
    private void useCustomBackground() {
        try {
            // Load background image
            java.awt.image.BufferedImage bg = javax.imageio.ImageIO.read(
                getClass().getResource("/images/Option5.png")
            );

            // Create background panel
            ImageRenderComponent bgPanel = new ImageRenderComponent(bg);
            bgPanel.setLayout(new java.awt.BorderLayout());

            // Makes jPanel transparent so background shows through
            jPanel1.setOpaque(false);

            // Puts existing jPanel1 on top of the background
            bgPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

            // Replace the frame’s content pane with the background panel
            setContentPane(bgPanel);
            pack(); // resize window correctly
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void setLoggedInUser(String InstID, String Role, String FName, String MName, String LName) {
        // Save to fields for later use
        this.InstID = InstID;
        this.Role = Role;
        this.FName = FName;
        this.MName = MName;
        this.LName = LName;
        
        this.loggedInInstID = InstID;
    }

    private void initConnection() {
        try {
            conn = DBConfig.getConnection();
            dao = new StudentRepo(conn);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Database connection failed!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Connection getConnection() {
        return conn;
    }
    
    // EDIT: Added setters so we can pass connection and instructor ID when re-opening the frame
    public void setConnection(Connection conn) {
        this.conn = conn;
    }

    public void setInstructorID(String instID) {
        this.InstID = instID;
    }
    
    private void initIntegration() {
        if (conn == null || loggedInInstID == null) return;
        classTable.loadData(loggedInInstID, null, null, null, null, conn);
        classTable.attachFilters(comboCourse, comboSubject, comboYear, comboSection, loggedInInstID, conn);
        attachClassTableEditPopup();
    }

    private void attachClassTableEditPopup() {
        JPopupMenu popup = new JPopupMenu();
        JMenuItem editItem = new JMenuItem("Edit");
        popup.add(editItem);

        JTable table = classTable.getTable(); // ensure customElements.Classes exposes getTable()
        table.setComponentPopupMenu(popup);

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = table.rowAtPoint(e.getPoint());
                if (row != -1) table.setRowSelectionInterval(row, row);
            }
        });

        editItem.addActionListener(e -> {
            RowToStudentMapper classesMapper = (model, modelRow) -> {
                String studID  = UiUtils.safeToString(model.getValueAt(modelRow, 0)); // if present
                String lname   = UiUtils.safeToString(model.getValueAt(modelRow, 1));
                String fname   = UiUtils.safeToString(model.getValueAt(modelRow, 2));
                String mname   = UiUtils.safeToString(model.getValueAt(modelRow, 3));
                String course  = UiUtils.safeToString(model.getValueAt(modelRow, 4));
                String subject = UiUtils.safeToString(model.getValueAt(modelRow, 5));
                String year    = UiUtils.safeToString(model.getValueAt(modelRow, 6));
                String section = UiUtils.safeToString(model.getValueAt(modelRow, 7));
                return new StudentRow(studID, fname, mname, lname, subject, course, year, section);
            };

            StudentEditLauncher.openEditDialogFromTable(
                (Frame) SwingUtilities.getWindowAncestor(table),
                table,
                dao, // now StudentRepo
                classesMapper,
                () -> {
                    initIntegration(); // refresh after save
                }
            );
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customElements.NewButton AttendanceLog;
    private customElements.NewButton BLogout;
    private customElements.NewButton BViewProfile;
    private javax.swing.JLabel BackHome;
    private customElements.NewButton IDScanner;
    private customElements.Classes classTable;
    private customElements.RoundedComboBox comboCourse;
    private customElements.RoundedComboBox comboSection;
    private customElements.RoundedComboBox comboSubject;
    private customElements.RoundedComboBox comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelNavigation;
    private customElements.NewButton savePDF;
    // End of variables declaration//GEN-END:variables
}
