/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import customElements.Classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jobelle
 */
public class ViewClasses extends BaseFrame {
    
    private HomePage homePage;
    private Connection conn;
    private StudentRepo dao; // <- changed type
    private String loggedInInstID;
    private boolean integrationInitialized = false;
    
    // user info (needed by setLoggedInUser and other methods)
    private String InstID;
    private String Role;
    private String FName;
    private String MName;
    private String LName;

    public ViewClasses(HomePage homePage) {
        super(homePage);
        this.homePage = homePage;
        this.loggedInInstID = homePage.getInstructorID(); // initial
        initConnection();
        initComponents();
        initIntegration();
        setCenter();
        useCustomBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboYear = new customElements.RoundedComboBox();
        comboSection = new customElements.RoundedComboBox();
        savePDF = new customElements.NewButton();
        comboCourse = new customElements.RoundedComboBox();
        comboSubject = new customElements.RoundedComboBox();
        classTable = new customElements.Classes();
        BackHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IDScanner = new customElements.NewButton();
        AttendanceLog = new customElements.NewButton();
        BViewProfile = new customElements.NewButton();
        BLogout = new customElements.NewButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 17, 84));

        comboYear.setBackground(new java.awt.Color(228, 226, 226));
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1", "2", "3", "4" }));
        comboYear.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSection.setBackground(new java.awt.Color(228, 226, 226));
        comboSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section", "A", "B", "C", "D", "E" }));
        comboSection.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        savePDF.setText("Save as PDF");
        savePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePDFActionPerformed(evt);
            }
        });

        comboCourse.setBackground(new java.awt.Color(228, 226, 226));
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Course", "Computer Science", "Information Technology", "Bachelor in Library and Information Science", "Diploma in Computer Technology", " " }));
        comboCourse.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        comboSubject.setBackground(new java.awt.Color(228, 226, 226));
        comboSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject", "Object-Oriented Programming", " ", " " }));
        comboSubject.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        BackHome.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setText("< Home");
        BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Classes");

        IDScanner.setText("ID Scanner");
        IDScanner.setToolTipText("");
        IDScanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDScannerActionPerformed(evt);
            }
        });

        AttendanceLog.setText("Attendance Log");
        AttendanceLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceLogActionPerformed(evt);
            }
        });

        BViewProfile.setText("View Profile");
        BViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BViewProfileActionPerformed(evt);
            }
        });

        BLogout.setText("Logout");
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(37, 99, 235));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackHome)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(classTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(325, 325, 325)
                                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AttendanceLog, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttendanceLog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(IDScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(BackHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(classTable, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseClicked
        this.setVisible(false);
        homePage.setVisible(true);
    }//GEN-LAST:event_BackHomeMouseClicked

    private void IDScannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDScannerActionPerformed
        MainPageInst mp = new MainPageInst(homePage);
        mp.setLoggedInUser(this.InstID, this.Role, this.FName, this.MName, this.LName);
        mp.setVisible(true);
    }//GEN-LAST:event_IDScannerActionPerformed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        boolean logoutClicked = true;

        if (logoutClicked){
            this.dispose();

            LoginForm LF = new LoginForm();
            LF.setVisible(true);
        }
    }//GEN-LAST:event_BLogoutActionPerformed

    private void AttendanceLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceLogActionPerformed
        AttendanceLogInst AL = homePage.getAttendanceLogInst(); // reuse existing instance
        AL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AttendanceLogActionPerformed

    private void savePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePDFActionPerformed
        String course = (comboCourse.getSelectedIndex() > 0) ? comboCourse.getSelectedItem().toString().trim() : "";
        String year = (comboYear.getSelectedIndex() > 0) ? comboYear.getSelectedItem().toString().trim() : "";
        String section = (comboSection.getSelectedIndex() > 0) ? comboSection.getSelectedItem().toString().trim() : "";

        String classInfo = String.join(" ",
                (course.isEmpty() ? "" : course),
                (year.isEmpty() ? "" : year),
                (section.isEmpty() ? "" : section)
        ).trim();

        String title = "Class Masterlist" + (classInfo.isEmpty() ? "" : ("\n BS " + classInfo));

        JTable table = classTable.getTable();
        PDFExportUtil.exportTable(this, table, title);
    }//GEN-LAST:event_savePDFActionPerformed

    private void BViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BViewProfileActionPerformed
        dialogViewProfile dvp = new dialogViewProfile(this, true);
        dvp.setLoggedInUser(this.InstID, this.Role, this.FName, this.MName, this.LName);
        dvp.setVisible(true);
    }//GEN-LAST:event_BViewProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewClasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomePage homePage = new HomePage();  
                ViewClasses viewClass = new ViewClasses(homePage);
                viewClass.setVisible(true);
            }
        });
    }

    private void setCenter() {
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int left = (d.width - this.getWidth()) / 2;
        int top = (d.height - this.getHeight()) / 2;
        this.setLocation(left, top);
    }
    
    private void useCustomBackground() {
        try {
            // Load background image
            final java.awt.image.BufferedImage bg = javax.imageio.ImageIO.read(
                getClass().getResource("/images/headerQRrive.jpg")
            );

            javax.swing.JPanel bgPanel = new javax.swing.JPanel(new java.awt.BorderLayout()) {
                @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                    if (bg == null) return;

                    java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                    try {
                        // High quality rendering hints
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                                            java.awt.RenderingHints.VALUE_INTERPOLATION_BICUBIC);
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING,
                                            java.awt.RenderingHints.VALUE_RENDER_QUALITY);
                        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                        // Draw the background image scaled to fill the panel (maintain aspect if you prefer)
                        int w = getWidth();
                        int h = getHeight();
                        g2.drawImage(bg, 0, 0, w, h, this);
                    } finally {
                        g2.dispose();
                    }
                }
            };

            jPanel1.setOpaque(false);
            bgPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

            setContentPane(bgPanel);
            pack(); // resize window correctly
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
   @Override
    public void setLoggedInUser(String InstID, String Role, String FName, String MName, String LName) {
        this.InstID = InstID;
        this.Role = Role;
        this.FName = FName;
        this.MName = MName;
        this.LName = LName;

        // keep the internal loggedInInstID in sync
        this.loggedInInstID = InstID;

        // refresh UI pieces
        //displayName();
        // reload integration (table + combos)
        initIntegration();
    }

    private void initConnection() {
        try {
            conn = DBConfig.getConnection();
            dao = new StudentRepo(conn);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Database connection failed!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Connection getConnection() {
        return conn;
    }
    
    // EDIT: Added setters so we can pass connection and instructor ID when re-opening the frame
    public void setConnection(Connection conn) {
        this.conn = conn;
    }

    public void setInstructorID(String instID) {
        this.InstID = instID;
    }
    
    private void initIntegration() {
        if (conn == null || loggedInInstID == null) return;
        classTable.loadData(loggedInInstID, null, null, null, null, conn);
        populateFiltersForInstructor();

        if (!integrationInitialized) {
            classTable.attachFilters(comboCourse, comboSubject, comboYear, comboSection, loggedInInstID, conn);
            attachClassTableEditPopup();
            integrationInitialized = true;
        } else {
        }
    }
    
        /**
     * Populate comboCourse, comboSubject, comboYear and comboSection using StudentRepo for the current instructor.
     */
    private void populateFiltersForInstructor() {
        if (dao == null || loggedInInstID == null) return;

        List<String> courses = dao.listCoursesForInstructor(loggedInInstID);
        DefaultComboBoxModel<String> courseModel = new DefaultComboBoxModel<>();
        courseModel.addElement("Course");
        for (String c : courses) courseModel.addElement(c);
        comboCourse.setModel(courseModel);

        // Subjects: if at least one course exists, prefill subjects with all instructor subjects,
        // otherwise leave "Subject" only.
        DefaultComboBoxModel<String> subjectModel = new DefaultComboBoxModel<>();
        subjectModel.addElement("Subject");
        List<String> subjects = dao.listSubjectsForInstructor(loggedInInstID, null);
        for (String s : subjects) subjectModel.addElement(s);
        comboSubject.setModel(subjectModel);

        // Years
        DefaultComboBoxModel<String> yearModel = new DefaultComboBoxModel<>();
        yearModel.addElement("Year");
        List<String> years = dao.listYearsForInstructor(loggedInInstID);
        for (String y : years) yearModel.addElement(y);
        comboYear.setModel(yearModel);

        // Sections
        DefaultComboBoxModel<String> sectionModel = new DefaultComboBoxModel<>();
        sectionModel.addElement("Section");
        List<String> sections = dao.listSectionsForInstructor(loggedInInstID, null);
        for (String s : sections) sectionModel.addElement(s);
        comboSection.setModel(sectionModel);
    }

    private void attachClassTableEditPopup() {
        JPopupMenu popup = new JPopupMenu();
        JMenuItem editItem = new JMenuItem("Edit");
        popup.add(editItem);

        JTable table = classTable.getTable(); // ensure customElements.Classes exposes getTable()
        table.setComponentPopupMenu(popup);

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = table.rowAtPoint(e.getPoint());
                if (row != -1) table.setRowSelectionInterval(row, row);
            }
        });

        editItem.addActionListener(e -> {
            RowToStudentMapper classesMapper = (model, modelRow) -> {
                String studID  = UiUtils.safeToString(model.getValueAt(modelRow, 0)); // if present
                String lname   = UiUtils.safeToString(model.getValueAt(modelRow, 1));
                String fname   = UiUtils.safeToString(model.getValueAt(modelRow, 2));
                String mname   = UiUtils.safeToString(model.getValueAt(modelRow, 3));
                String course  = UiUtils.safeToString(model.getValueAt(modelRow, 4));
                String subject = UiUtils.safeToString(model.getValueAt(modelRow, 5));
                String year    = UiUtils.safeToString(model.getValueAt(modelRow, 6));
                String section = UiUtils.safeToString(model.getValueAt(modelRow, 7));
                return new StudentRow(studID, fname, mname, lname, subject, course, year, section);
            };

            StudentEditLauncher.openEditDialogFromTable(
                (Frame) SwingUtilities.getWindowAncestor(table),
                table,
                dao, // now StudentRepo
                classesMapper,
                () -> {
                    initIntegration(); // refresh after save
                }
            );
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customElements.NewButton AttendanceLog;
    private customElements.NewButton BLogout;
    private customElements.NewButton BViewProfile;
    private javax.swing.JLabel BackHome;
    private customElements.NewButton IDScanner;
    private customElements.Classes classTable;
    private customElements.RoundedComboBox comboCourse;
    private customElements.RoundedComboBox comboSection;
    private customElements.RoundedComboBox comboSubject;
    private customElements.RoundedComboBox comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private customElements.NewButton savePDF;
    // End of variables declaration//GEN-END:variables
}
